/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 10.4.13-MariaDB : Database - appdirectory
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `countries` */

DROP TABLE IF EXISTS `countries`;

CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(50) DEFAULT NULL,
  `country_code` char(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=250 DEFAULT CHARSET=utf8mb4;

/*Data for the table `countries` */

insert  into `countries`(`id`,`country_name`,`country_code`) values 
(1,'Afghanistan','AF\r'),
(2,'Ã…land Islands','AX\r'),
(3,'Albania','AL\r'),
(4,'Algeria','DZ\r'),
(5,'American Samoa','AS\r'),
(6,'Andorra','AD\r'),
(7,'Angola','AO\r'),
(8,'Anguilla','AI\r'),
(9,'Antarctica','AQ\r'),
(10,'Antigua and Barbuda','AG\r'),
(11,'Argentina','AR\r'),
(12,'Armenia','AM\r'),
(13,'Aruba','AW\r'),
(14,'Australia','AU\r'),
(15,'Austria','AT\r'),
(16,'Azerbaijan','AZ\r'),
(17,'Bahamas','BS\r'),
(18,'Bahrain','BH\r'),
(19,'Bangladesh','BD\r'),
(20,'Barbados','BB\r'),
(21,'Belarus','BY\r'),
(22,'Belgium','BE\r'),
(23,'Belize','BZ\r'),
(24,'Benin','BJ\r'),
(25,'Bermuda','BM\r'),
(26,'Bhutan','BT\r'),
(27,'Bolivia - Plurinational State of','BO\r'),
(28,'Bonaire - Sint Eustatius and Saba','BQ\r'),
(29,'Bosnia and Herzegovina','BA\r'),
(30,'Botswana','BW\r'),
(31,'Bouvet Island','BV\r'),
(32,'Brazil','BR\r'),
(33,'British Indian Ocean Territory','IO\r'),
(34,'Brunei Darussalam','BN\r'),
(35,'Bulgaria','BG\r'),
(36,'Burkina Faso','BF\r'),
(37,'Burundi','BI\r'),
(38,'Cambodia','KH\r'),
(39,'Cameroon','CM\r'),
(40,'Canada','CA\r'),
(41,'Cape Verde','CV\r'),
(42,'Cayman Islands','KY\r'),
(43,'Central African Republic','CF\r'),
(44,'Chad','TD\r'),
(45,'Chile','CL\r'),
(46,'China','CN\r'),
(47,'Christmas Island','CX\r'),
(48,'Cocos (Keeling) Islands','CC\r'),
(49,'Colombia','CO\r'),
(50,'Comoros','KM\r'),
(51,'Congo','CG\r'),
(52,'Congo - the Democratic Republic of the','CD\r'),
(53,'Cook Islands','CK\r'),
(54,'Costa Rica','CR\r'),
(55,'CÃ´te d\'Ivoire','CI\r'),
(56,'Croatia','HR\r'),
(57,'Cuba','CU\r'),
(58,'CuraÃ§ao','CW\r'),
(59,'Cyprus','CY\r'),
(60,'Czech Republic','CZ\r'),
(61,'Denmark','DK\r'),
(62,'Djibouti','DJ\r'),
(63,'Dominica','DM\r'),
(64,'Dominican Republic','DO\r'),
(65,'Ecuador','EC\r'),
(66,'Egypt','EG\r'),
(67,'El Salvador','SV\r'),
(68,'Equatorial Guinea','GQ\r'),
(69,'Eritrea','ER\r'),
(70,'Estonia','EE\r'),
(71,'Ethiopia','ET\r'),
(72,'Falkland Islands (Malvinas)','FK\r'),
(73,'Faroe Islands','FO\r'),
(74,'Fiji','FJ\r'),
(75,'Finland','FI\r'),
(76,'France','FR\r'),
(77,'French Guiana','GF\r'),
(78,'French Polynesia','PF\r'),
(79,'French Southern Territories','TF\r'),
(80,'Gabon','GA\r'),
(81,'Gambia','GM\r'),
(82,'Georgia','GE\r'),
(83,'Germany','DE\r'),
(84,'Ghana','GH\r'),
(85,'Gibraltar','GI\r'),
(86,'Greece','GR\r'),
(87,'Greenland','GL\r'),
(88,'Grenada','GD\r'),
(89,'Guadeloupe','GP\r'),
(90,'Guam','GU\r'),
(91,'Guatemala','GT\r'),
(92,'Guernsey','GG\r'),
(93,'Guinea','GN\r'),
(94,'Guinea-Bissau','GW\r'),
(95,'Guyana','GY\r'),
(96,'Haiti','HT\r'),
(97,'Heard Island and McDonald Islands','HM\r'),
(98,'Holy See (Vatican City State)','VA\r'),
(99,'Honduras','HN\r'),
(100,'Hong Kong','HK\r'),
(101,'Hungary','HU\r'),
(102,'Iceland','IS\r'),
(103,'India','IN\r'),
(104,'Indonesia','ID\r'),
(105,'Iran - Islamic Republic of','IR\r'),
(106,'Iraq','IQ\r'),
(107,'Ireland','IE\r'),
(108,'Isle of Man','IM\r'),
(109,'Israel','IL\r'),
(110,'Italy','IT\r'),
(111,'Jamaica','JM\r'),
(112,'Japan','JP\r'),
(113,'Jersey','JE\r'),
(114,'Jordan','JO\r'),
(115,'Kazakhstan','KZ\r'),
(116,'Kenya','KE\r'),
(117,'Kiribati','KI\r'),
(118,'Korea - Democratic People\'s Republic of','KP\r'),
(119,'Korea - Republic of','KR\r'),
(120,'Kuwait','KW\r'),
(121,'Kyrgyzstan','KG\r'),
(122,'Lao People\'s Democratic Republic','LA\r'),
(123,'Latvia','LV\r'),
(124,'Lebanon','LB\r'),
(125,'Lesotho','LS\r'),
(126,'Liberia','LR\r'),
(127,'Libya','LY\r'),
(128,'Liechtenstein','LI\r'),
(129,'Lithuania','LT\r'),
(130,'Luxembourg','LU\r'),
(131,'Macao','MO\r'),
(132,'Macedonia - the Former Yugoslav Republic of','MK\r'),
(133,'Madagascar','MG\r'),
(134,'Malawi','MW\r'),
(135,'Malaysia','MY\r'),
(136,'Maldives','MV\r'),
(137,'Mali','ML\r'),
(138,'Malta','MT\r'),
(139,'Marshall Islands','MH\r'),
(140,'Martinique','MQ\r'),
(141,'Mauritania','MR\r'),
(142,'Mauritius','MU\r'),
(143,'Mayotte','YT\r'),
(144,'Mexico','MX\r'),
(145,'Micronesia - Federated States of','FM\r'),
(146,'Moldova - Republic of','MD\r'),
(147,'Monaco','MC\r'),
(148,'Mongolia','MN\r'),
(149,'Montenegro','ME\r'),
(150,'Montserrat','MS\r'),
(151,'Morocco','MA\r'),
(152,'Mozambique','MZ\r'),
(153,'Myanmar','MM\r'),
(154,'Namibia','NA\r'),
(155,'Nauru','NR\r'),
(156,'Nepal','NP\r'),
(157,'Netherlands','NL\r'),
(158,'New Caledonia','NC\r'),
(159,'New Zealand','NZ\r'),
(160,'Nicaragua','NI\r'),
(161,'Niger','NE\r'),
(162,'Nigeria','NG\r'),
(163,'Niue','NU\r'),
(164,'Norfolk Island','NF\r'),
(165,'Northern Mariana Islands','MP\r'),
(166,'Norway','NO\r'),
(167,'Oman','OM\r'),
(168,'Pakistan','PK\r'),
(169,'Palau','PW\r'),
(170,'Palestine - State of','PS\r'),
(171,'Panama','PA\r'),
(172,'Papua New Guinea','PG\r'),
(173,'Paraguay','PY\r'),
(174,'Peru','PE\r'),
(175,'Philippines','PH\r'),
(176,'Pitcairn','PN\r'),
(177,'Poland','PL\r'),
(178,'Portugal','PT\r'),
(179,'Puerto Rico','PR\r'),
(180,'Qatar','QA\r'),
(181,'RÃ©union','RE\r'),
(182,'Romania','RO\r'),
(183,'Russian Federation','RU\r'),
(184,'Rwanda','RW\r'),
(185,'Saint BarthÃ©lemy','BL\r'),
(186,'Saint Helena - Ascension and Tristan da Cunha','SH\r'),
(187,'Saint Kitts and Nevis','KN\r'),
(188,'Saint Lucia','LC\r'),
(189,'Saint Martin (French part)','MF\r'),
(190,'Saint Pierre and Miquelon','PM\r'),
(191,'Saint Vincent and the Grenadines','VC\r'),
(192,'Samoa','WS\r'),
(193,'San Marino','SM\r'),
(194,'Sao Tome and Principe','ST\r'),
(195,'Saudi Arabia','SA\r'),
(196,'Senegal','SN\r'),
(197,'Serbia','RS\r'),
(198,'Seychelles','SC\r'),
(199,'Sierra Leone','SL\r'),
(200,'Singapore','SG\r'),
(201,'Sint Maarten (Dutch part)','SX\r'),
(202,'Slovakia','SK\r'),
(203,'Slovenia','SI\r'),
(204,'Solomon Islands','SB\r'),
(205,'Somalia','SO\r'),
(206,'South Africa','ZA\r'),
(207,'South Georgia and the South Sandwich Islands','GS\r'),
(208,'South Sudan','SS\r'),
(209,'Spain','ES\r'),
(210,'Sri Lanka','LK\r'),
(211,'Sudan','SD\r'),
(212,'Suriname','SR\r'),
(213,'Svalbard and Jan Mayen','SJ\r'),
(214,'Swaziland','SZ\r'),
(215,'Sweden','SE\r'),
(216,'Switzerland','CH\r'),
(217,'Syrian Arab Republic','SY\r'),
(218,'Taiwan - Province of China','TW\r'),
(219,'Tajikistan','TJ\r'),
(220,'Tanzania - United Republic of','TZ\r'),
(221,'Thailand','TH\r'),
(222,'Timor-Leste','TL\r'),
(223,'Togo','TG\r'),
(224,'Tokelau','TK\r'),
(225,'Tonga','TO\r'),
(226,'Trinidad and Tobago','TT\r'),
(227,'Tunisia','TN\r'),
(228,'Turkey','TR\r'),
(229,'Turkmenistan','TM\r'),
(230,'Turks and Caicos Islands','TC\r'),
(231,'Tuvalu','TV\r'),
(232,'Uganda','UG\r'),
(233,'Ukraine','UA\r'),
(234,'United Arab Emirates','AE\r'),
(235,'United Kingdom','GB\r'),
(236,'United States','US\r'),
(237,'United States Minor Outlying Islands','UM\r'),
(238,'Uruguay','UY\r'),
(239,'Uzbekistan','UZ\r'),
(240,'Vanuatu','VU\r'),
(241,'Venezuela - Bolivarian Republic of','VE\r'),
(242,'Viet Nam','VN\r'),
(243,'Virgin Islands - British','VG\r'),
(244,'Virgin Islands - U.S.','VI\r'),
(245,'Wallis and Futuna','WF\r'),
(246,'Western Sahara','EH\r'),
(247,'Yemen','YE\r'),
(248,'Zambia','ZM\r'),
(249,'Zimbabwe','ZW');

/*Table structure for table `customer_data_log` */

DROP TABLE IF EXISTS `customer_data_log`;

CREATE TABLE `customer_data_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_source` smallint(2) DEFAULT NULL,
  `response` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `customer_data_log` */

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `document` varchar(20) DEFAULT NULL,
  `email` varchar(40) DEFAULT NULL,
  `country_code` char(4) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`document`,`email`,`country_code`,`password`,`created_at`,`updated_at`,`enabled`) values 
(1,'Pedro Gomez','123456789','pedro@prueba.com','CO','6817a8c319cb881e2e53372baf40320c','2020-08-16 21:47:46','2020-08-16 21:47:46',1),
(2,'Federico Gomez','24681012','federico@desarrollo.com','CO','1b3dc5419612ca29b01d3340720e918a','2020-08-17 06:12:38','2020-08-17 06:12:38',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
